version: "3.7"
services:

  postgres-db:
      image: "postgres:latest"
      restart: always
      container_name: "postgres-db-dell"
      volumes: 
        - C:/Users/monassakorc/Documents/data_engineering_challenge/postgres/data:/var/lib/postgresql/data #PGDATA
      environment: 
        PGDATA: /var/lib/postgresql/data
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: dell
      ports: 
        - "5432:5432"